K: 10  # number of nodes
Mk: 6  # number of sensors per node
D: 1  # number of target signal channels
# Scenario 1: full 
# Qdglob: 2  # number of global desired sources
# Qnglob: 2  # number of global noise sources
# Qdloc: 5  # number of local desired sources
# Qnloc: 5  # number of local noise sources
# Scenario 2: specific for TI-iDANSE 
# Qdglob: 2  # number of global desired sources
# Qnglob: 3  # number of global noise sources
# Qdloc: 5  # number of local desired sources
# Qnloc: 5  # number of local noise sources
# Scenario 3: for POSS 
Qdglob: 2  # number of global desired sources
Qnglob: 2  # number of global noise sources
Qdloc: 0  # number of local desired sources
Qnloc: 0  # number of local noise sources

graphDiameter: null  # diameter of the graph corresponding to the network
graphDiameter: 2  # diameter of the graph corresponding to the network

algos:  # list of algorithms to run
- centralized
- idanse
- tiidanse
- tidmwf
# observability: poss  # "foss" for fully overlapping subspaces,
observability: foss  # "foss" for fully overlapping subspaces,
    # "poss" for partially overlapping subspaces
# possDiffuse: True  # if True and observability is 'foss', the
possDiffuse: False  # if True and observability is 'foss', the
    # noise sources are assumed only local, i.e., uncorrelated across nodes

seed: 42  # random number generator seed