# WASN parameters
K: 6  # number of nodes
# Mk: 1  # number of sensors per node
Mk:  # number of sensors per node
- 1
- 2
- '10--'
graphDiameter: null  # diameter of the graph corresponding to the network

# Acoustic scenario parameters
Qd: 2  # number of desired sources
Qn: 2  # number of noise sources
D: 1  # number of target signal channels
###########################
# domain: time  # domain of the signals, 'time', or 'time_complex', or 'wola'
domain: wola  # domain of the signals, 'time', or 'time_complex', or 'wola'
# domain: time_complex  # domain of the signals, 'time', or 'time_complex', or 'wola'
##########################
TDsteeringMats: random  # type of steering matrices in time domain
# TDsteeringMats: anechoic  # type of steering matrices in time domain
roomLength: 5.0  # length of the room in meters
roomWidth: 5.0   # width of the room in meters
roomHeight: 3.0   # height of the room in meters
nodeRadius: 0.03  # radius of the node in meters
onPlane: True  # if True, all elements are on the same plane
# onPlane: False  # if True, all elements are on the same plane
# t60: 0.          # reverberation time in seconds
t60: 0.2          # reverberation time in seconds
minDistFromWall: 0.25  # minimum distance from the wall in meters
minDistNodeSource: 1  # minimum distance from any node to a source in meters
# observabilityCriterion: raw_distance  # criterion for computing observability
observabilityCriterion: hierarchical  # criterion for computing observability
    # 'raw_distance': based on the distance between nodes and sources
    # 'hierarchical': starting from full observability, then removing observability connections starting from the largest node-source distance
# hierarchicalObsPruningThrs: 0.5  # for 'hierarchical' `observabilityCriterion`, threshold for pruning observability connections
hierarchicalObsPruningThrs: 1  # for 'hierarchical' `observabilityCriterion`, threshold for pruning observability connections
    # if 0, no pruning is done
    # if 1, all possible observability connections are pruned, down to minimum criterion (observabilityCriterion = 'raw_distance')
    # intermediate values stop the pruning between 0 and 1.
# maxDistForObservability: 0.05  # minimum distance for observability in meters
maxDistForObservability: null  # minimum distance for observability in meters
latentSNR: 0.0  # SNR between the latent desired signals and the latent noise signals in dB
# latentSNR: -5.0  # SNR between the latent desired signals and the latent noise signals in dB
diffuseSNR: -9999.0  # SNR between the latent desired signals and the diffuse noise signals in dB
# diffuseSNR: -10.0  # SNR between the latent desired signals and the diffuse noise signals in dB
# diffuseSNR: -5.0  # SNR between the latent desired signals and the diffuse noise signals in dB
# diffuseSNR: 0.0  # SNR between the latent desired signals and the diffuse noise signals in dB
commDist: 1.5  # communication distance [m] (used at ad-hoc topology initialization, but `connectivity` plays a role)
connectivity: 0.5  # amount of ad-hoc topology connectivity
# pruningStrategy: star  # tree-pruning strategy
pruningStrategy: mst  # tree-pruning strategy
# pruningStrategy: mmut  # tree-pruning strategy
# pruningStrategy: line  # tree-pruning strategy
    # 'star': star topology with updating node as root
    # 'mst': minimum spanning tree
    # 'mmut': MMUT pruning with updating node as root
    # 'line': line topology with updating node as root
nfft: 1024  # number of FFT points
nhop: 512  # number of samples in FFT hop
# nfft: 512  # number of FFT points
# nhop: 256  # number of samples in FFT hop
win: hann  # STFT window type
# win: rect  # STFT window type
dynamics: static  # type of acoustic scenario dynamics
# dynamics: moving  # type of acoustic scenario dynamics
    # 'static' for static scenario,
    # 'moving' for dynamic scenario with always-active sources and random source movements
    # 'switching' for dynamic scenario with sources that can appear and disappear
movingEvery: 10.0  # time in seconds after which sources move in `moving` scenarios
# movingEvery: 5.0  # time in seconds after which sources move in `moving` scenarios
fixedObservabilities: True  # if True, the observabilities are fixed

# Signals parameters
# fs: 41000  # sampling frequency
fs: 16000  # sampling frequency
# fs: 8000  # sampling frequency
# T: 0.05  # duration of the signals in seconds
# T: 2.0  # duration of the signals in seconds
# T: 15.0  # duration of the signals in seconds
T: 30.0  # duration of the signals in seconds
# T: 60.0  # duration of the signals in seconds
# T: 120.0  # duration of the signals in seconds
# T: 200.0  # duration of the signals in seconds
# selfNoiseFactor: 0.000001  # self-noise factor, used to scale the noise covariance
selfNoiseFactor: 0.01  # self-noise factor, used to scale the noise covariance
# selfNoiseFactor: 0.1  # self-noise factor, used to scale the noise covariance
# selfNoiseFactor: 1  # self-noise factor, used to scale the noise covariance
# noiseSigType: ssn  # random, babble, or ssn
# noiseSigType: random  # random, babble, or ssn
# desSigType: random  # speech or noise
noiseSigType: babble  # random, babble, or ssn
desSigType: speech  # speech or noise
ssnDatabasePath: "C:/Users/pdidier/Dropbox/PC/Documents/sounds-phd/02_data/00_raw_signals/02_noise/ssn"  # path to the SSN database
babbleDatabasePath: "C:/Users/pdidier/Dropbox/_BELGIUM/KUL/SOUNDS_PhD/02_research/03_simulations/02_python/01_local_only/01_algorithms/04_dMWF/sound_files/babble"  # path to the babble database
# speechDatabasePath: "C:/Users/pdidier/Dropbox/_BELGIUM/KUL/SOUNDS_PhD/02_research/03_simulations/99_datasets/01_signals/01_LibriSpeech_ASR/test-clean"
speechDatabasePath: "C:/Users/pdidier/Documents/datasets/DS_10283_3443/VCTK-Corpus-0.92/wav48_silence_trimmed"

# Algorithm(s) parameters
algos:  # list of algorithms to run
- unprocessed
- local
- centralized
- dmwf
- danse
- rsdanse
# - tidmwf
# - tidanse
maxDANSEiter: 30  # maximum number of iterations for DANSE
# maxDANSEiter: 10  # maximum number of iterations for DANSE
mu: 1  # SDW-MWF factor
# mu: 10  # SDW-MWF factor
# gevd: True  # if True, use GEV decomposition instead of regular MWF in estimation filters
gevd: False  # if True, use GEV decomposition instead of regular MWF in estimation filters
# DANSEiterEveryXframes: 20  # DANSE iteration every X frames
# DANSEiterEveryXframes: -1  # DANSE iteration every X frames
DANSEiterEveryXframes: 10  # DANSE iteration every X frames
#   ^^^ if useVAD is True, new DANSE iteration as soon as both Ryy and Rnn have both been updated at least X times.
#   ^^^ if -1, new DANSE iteration every frame, regardless of useVAD 
dMWFalternating: True  # if True, use alternating discovery/estimation steps in dMWF
# dMWFalternating: False  # if True, use alternating discovery/estimation steps in dMWF

# VAD parameters
useVAD: True  # if True, update the SCMs based on a VAD decision
# useVAD: False  # if True, update the SCMs based on a VAD decision
noiseONOFFperiod: 1  # period of noise ON/OFF switching in seconds (only used if `useVAD` is True and desired signals are `random`)
vadThreshold: 0.1  # threshold for VAD decision, relative to the energy of the latent desired signal
vadSmoothingPeriod: 0.2  # smoothing period for VAD decision [s]

# Online mode parameters
# frameDuration: 0.5  # length of the frame in seconds (for time-domain processing, otherwise using WOLA frames)
beta: {
    # default: 0.975,
    # default: 0.9,
    # default: 0.985,
    default: 0.99,
    # dmwf: 0.95,
}  # forgetting factor for online processing

# Debug
singleLine: null  # if not None, only process this frequency line in WOLA domain
# singleLine: 20  # if not None, only process this frequency line in WOLA domain
# unconstrainedRandomPositions: True  # if True, allow random positions for sources
unconstrainedRandomPositions: False  # if True, allow random positions for sources
# wolaMixtures_viaTD: False  # if True, build WOLA mixtures (final mic signals) via time-domain processing, then STFT. Otherwise, build directly in the WOLA domain via STFT of latent signals.
wolaMixtures_viaTD: True  # if True, build WOLA mixtures (final mic signals) via time-domain processing, then STFT. Otherwise, build directly in the WOLA domain via STFT of latent signals.
# noCrossCorrelation: True  # if True, build Ryy as Rss + Rnn exactly, i.e., mimick zero correlation between desired and noise sources
noCrossCorrelation: False  # if True, build Ryy as Rss + Rnn exactly, i.e., mimick zero correlation between desired and noise sources
# nodeSpecificDANSEsourceEnum: True  # if True, use a node-specific enumeration for DANSE desired sources (dimension of fused signals = Q_{d,k})
nodeSpecificDANSEsourceEnum: False  # if True, use a node-specific enumeration for DANSE desired sources (dimension of fused signals = Q_{d,k})

# General simulation set parameters
# nMCruns: 1  # number of Monte Carlo runs
nMCruns: 6  # number of Monte Carlo runs
seed: 45  # random number generator seed
suffix: test  # output file suffix